{
 "title": "Spring Boot – Overview",
 "time": { "from": "2026-01-28T17:29:17.088Z", "to": "2026-01-28T17:29:40.839Z" },
 "panels": [
  {
   "title": "Application logs",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"spring\"}"
    }
   ]
  },
  {
   "title": "GC pause rate (Time series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=\"FinalProjectLedZeppelin\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App UP (Stat)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "up{job=\"spring\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap used (Time series, MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"FinalProjectLedZeppelin\",area=\"heap\"}) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS (Time series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"FinalProjectLedZeppelin\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p95 (Time series, seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (rate(http_server_requests_seconds_bucket{application=\"FinalProjectLedZeppelin\"}[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx errors / sec (Time series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"FinalProjectLedZeppelin\",status=~\"5..\"}[1m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx ratio % (Time series)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 35 },
   "targets": [
    {
     "expr": "(\r\n  100 *\r\n  sum(rate(http_server_requests_seconds_count{application=\"FinalProjectLedZeppelin\",status=~\"5..\"}[5m]))\r\n  /\r\n  sum(rate(http_server_requests_seconds_count{application=\"FinalProjectLedZeppelin\"}[5m]))\r\n) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}